devfreq: devbw: Do a full checkout to e4d5b2d5a633
This code isn't even used (ab-percent isn't anywhere in the device
tree).

Fixes an unused function warning:
../drivers/devfreq/devfreq_devbw.c:134:12: error: unused function 'devbw_target_cpubw' [-Werror,-Wunused-function]

The relevant part of commit 4dd208de3de1 ("BACKPORT: treewide:
devm_kzalloc() -> devm_kcalloc()") was reapplied.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>
Signed-off-by: mcdachpappe <noreference@web.de>