drivers: usb: Fix compiler warning
Introduced in commit https://github.com/OnePlusOSS/android_kernel_oneplus_sdm845/commit/f7be625a0541e8cd114fd0e9c5f4857ee9fe57c1
drivers/usb/pd/policy_engine.c:899:29: error: unused variable 'val' [-Werror,-Wunused-variable]

Signed-off-by: mcdachpappe <noreference@web.de>